// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAda3WaeLvGNF_J2nZt2GpJhFjWv3_asLw',
    appId: '1:561130277695:web:6ba35d2df9fa73bbd4218a',
    messagingSenderId: '561130277695',
    projectId: 'cpsc5250hw',
    authDomain: 'cpsc5250hw.firebaseapp.com',
    storageBucket: 'cpsc5250hw.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwEA8NnO9LIOQW5BYLiGVLTjcA3-uNKA0',
    appId: '1:561130277695:android:1bda66fa703bcf4fd4218a',
    messagingSenderId: '561130277695',
    projectId: 'cpsc5250hw',
    storageBucket: 'cpsc5250hw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxx3Iv9oxRK8bcCKAXMiaEUIr5fmLFUCo',
    appId: '1:561130277695:ios:56471a829d642776d4218a',
    messagingSenderId: '561130277695',
    projectId: 'cpsc5250hw',
    storageBucket: 'cpsc5250hw.appspot.com',
    iosBundleId: 'com.example.cpsc5250hw',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxx3Iv9oxRK8bcCKAXMiaEUIr5fmLFUCo',
    appId: '1:561130277695:ios:001773fe5a357222d4218a',
    messagingSenderId: '561130277695',
    projectId: 'cpsc5250hw',
    storageBucket: 'cpsc5250hw.appspot.com',
    iosBundleId: 'com.example.cpsc5250hw.RunnerTests',
  );
}
